---

- name: Adicionar PPA à lista de repositórios 
  apt_repository:
    repo: 'ppa:gluster/glusterfs-{{ glusterfs_ppa_version }}'
    state: present
    update_cache: yes
  register: glusterfs-ppa-adicionado
  when: glusterfs-ppa-em_uso

- name: Garantir uma reinstalação limpa do GlusterFS.
  apt:
    name: ['glusterfs-client', 'glusterfs-server']
    state: absent
  when: glusterfs-ppa-adicionado.changed

- name: Instalar GlusterFS (client e server)
  apt:
    name: ['glusterfs-client', 'glusterfs-server']
    state: present
    update_cache: true